# Generated by Django 5.2.1 on 2025-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
