# Generated by Django 5.2.1 on 2025-05-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='test',
            new_name='text',
        ),
    ]
